---
- name: Playbook de exemplo - Teste AWX
  hosts: all
  become: yes

  tasks:
    - name: Verificar conexão com os hosts
      ping:

    - name: Criar arquivo de teste
      copy:
        dest: /tmp/arquivo_criado_pelo_awx.txt
        content: "Esse arquivo foi criado via AWX com sucesso em {{ ansible_hostname }}\n"
